"undefined"===typeof Filters&&(Filters={});Filters.grayscale=function(a){for(var c=a.data,b=0;b<c.length;b+=4)c[b]=c[b+1]=c[b+2]=0.2126*c[b]+0.7152*c[b+1]+0.0722*c[b+2];return a};Filters.grayscaleRG=function(a){for(var c=a.data,b=0;b<c.length;b+=4)c[b]=c[b+1]=c[b+2]=(c[b]+c[b+1])/2;return a};Filters.thresholdRG=function(a,c){for(var b=a.data,e,d=0;d<b.length;d+=4)e=b[d]+b[d+1]>>1>c.threshold?255:0,b[d]=0,b[d+1]=e,b[d+2]=0,b[d+3]=e;return a};
if("undefined"!==typeof isCanvasSupported&&isCanvasSupported())Filters.tmpCanvas=document.createElement("canvas"),Filters.tmpCtx=Filters.tmpCanvas.getContext("2d");Filters.createImageData=function(a,c){return this.tmpCtx.createImageData(a,c)};
Filters.convolute=function(a,c,b){for(var e=Math.round(Math.sqrt(c.length)),d=Math.floor(e/2),f=a.data,h=a.width,a=a.height,i=Filters.createImageData(h,a),g=i.data,b=b?1:0,j=0;j<a;j++)for(var l=0;l<h;l++){for(var k=j,n=l,m=4*(j*h+l),o=0,p=0,v=0,s=0,t=0;t<e;t++)for(var u=0;u<e;u++){var q=k+t-d,r=n+u-d;0<=q&&q<a&&0<=r&&r<h&&(q=4*(q*h+r),r=c[t*e+u],o+=f[q]*r,p+=f[q+1]*r,v+=f[q+2]*r,s+=f[q+3]*r)}g[m]=o;g[m+1]=p;g[m+2]=v;g[m+3]=s+b*(255-s)}return i};
Filters.fastGaussian=function(a){for(var c=[0.06,0.061,0.242,0.383,0.242,0.061,0.06],b=a.data,e=a.width,a=a.height,d=Filters.createImageData(e,a).data,f=d,h=0;h<a;h++)for(var i=0;i<e;i++){for(var g=0,j=0,l=0,k=4*(h*e+i-3),n=0;n<c.length;n++){var m=c[n],g=g+b[k++]*m,j=j+b[k++]*m,l=l+b[k++]*m;k++}k=4*(h*e+i);f[k++]=g;f[k++]=j;f[k++]=l;f[k]=255}b=d;d=Filters.createImageData(e,a);f=d.data;for(h=0;h<a;h++)for(i=0;i<e;i++){l=j=g=0;k=4*((h-3)*e+i);for(n=0;n<c.length;n++)var m=c[n]/1.109,o=k+4*n*e,g=g+b[o++]*
m,j=j+b[o++]*m,l=l+b[o]*m;k=4*(h*e+i);f[k++]=g;f[k++]=j;f[k++]=l;f[k]=255}return d};Filters.compressedGrayScaleFromRedGreen=function(a){for(var c=a.data,b=[],e=a.width*a.height,d=0,f=0;f<e;f++)b[f]=(c[d]+c[d+1])/2,d+=4;return{data:b,width:a.width,height:a.height}};Filters.compressedGrayScaleFromRedGreenBlue=function(a){for(var c=a.data,b=[],e=a.width*a.height,d=0,f=0;f<e;f++)b[f]=0.2126*c[d]+0.7152*c[d+1]+0.0722*c[d+2],d+=4;return{data:b,width:a.width,height:a.height}};
Filters.compressedGrayScaleFromRed=function(a){for(var c=a.data,b=[],e=a.width*a.height,d=0,f=0;f<e;f++)b[f]=c[d],d+=4;return{data:b,width:a.width,height:a.height}};Filters.imageDataFromCompressedGrayScale=function(a){for(var c=Filters.createImageData(a.width,a.height),b=a.data,a=a.width*a.height,e=c.data,d=0,f=0;f<a;f++)e[d]=e[d+1]=e[d+2]=b[f],e[d+3]=255,d+=4;return c};Filters.meanCGSRepeated=function(a,c,b,e){for(var d=0;d<b;d++)a=Filters.meanCGS(a,c),e&&e(d/b);return a};
Filters.meanCGS=function(a,c){return Filters.meanCGSHorizontal(Filters.meanCGSVertical(a,c),c)};Filters.meanCGSHorizontal=function(a,c){var b=a.data,e=a.width*a.height,d=[],f=0,h=0;initArray(d,e);for(var i=Math.floor(c/2),g=c;g<e;g++)f=f+b[g]-b[h++],d[g-i]=f/c;return{data:d,width:a.width,height:a.height}};
Filters.meanCGSVertical=function(a,c){var b=a.data,e=a.width,d=a.height,f=e*d,h=[];initArray(h,f);for(var i=Math.floor(c/2),g=0;g<e;g++)for(var j=0,l=g-i*e,k=g+(i+1)*e,n=g,m=0;m<d;m++)j=j+(k<f?b[k]:0)-(0<=l?b[l]:0),h[n+e]=j/c,l+=e,k+=e,n+=e;return{data:h,width:a.width,height:a.height}};
Filters.peaksCGSOld=function(a,c){var b=a.data,e=a.width,d=a.height,f=[];initArray(f,e*d);for(var h=0;h<e;h++)for(var i=0;i<d;i++){var g=i*e+h,j=b[g];j>c&&j>=b[g+1]&&j>=b[g-1]&&j>=b[g-e]&&j>=b[g+e]&&(f[g]=255)}return{data:f,width:a.width,height:a.height}};
Filters.peaksCGS=function(a,c,b){var e=a.data,d=a.width,f=a.height,h=[],i=[];initArray(i,d*f);for(var g=0;g<d;g++)for(var j=0;j<f;j++){var l=j*d+g,k=e[l];if(k>=c){i[l]=255;var n=Math.min(g+b,d),m=Math.max(g-b,0);a:for(;m<n;m++)for(var o=Math.min(j+b,f),p=Math.max(j-b,0);p<o;p++)if(k<e[p*d+m]&&(g!=m||j!=p)){i[l]=0;break a}255==i[l]&&h.push({x:g,y:j})}}return{data:i,width:a.width,height:a.height,peaks:h}};
Filters.thresholdCGS=function(a,c){for(var b=a.data,e=a.width,d=a.height,f=[],h=0;h<e;h++)for(var i=0;i<d;i++){var g=i*e+h;f[g]=b[g]>=c?255:0}return{data:f,width:a.width,height:a.height}};function initArray(a,c){for(var b=0;b<c;b++)a[b]=0};(function(){var a;"undefined"===typeof Filters&&importScripts("filters-fast.js");addEventListener("message",function(c){var b,c=c.data;switch(c.cmd){case "start":return postMessage("WORKER STARTED: "+c.msg);case "autocount":return b="whiteOnBlue"===c.imageType?Filters.compressedGrayScaleFromRedGreen(c.imageData):Filters.compressedGrayScaleFromRedGreenBlue(c.imageData),a(0.1),b=Filters.meanCGSRepeated(b,5,4,function(b){return a(0.7*b+0.1)}),a(0.8),b=Filters.peaksCGS(b,c.threshold,3),a(1),postMessage({cmd:"autocount",
result:b.peaks})}},!1);a=function(a){return postMessage({cmd:"autocountProgress",result:a})}}).call(this);
